
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from "@/components/theme-provider"
import TopBar from '@/components/navbar/nav'
import { AccordionLeftbar } from '@/tools/accordance'
import { Suspense } from 'react'
import { Card } from '@/components/ui/card'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Under the hood',
  description: 'Generated by the UoNs',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ThemeProvider
            attribute="class"
            defaultTheme="system"
          >
            <TopBar /> 
            <div className="flex h-screen ">
            <section className='hidden md:hidden left-0 fixed w-[15%] px-2 h-[100vh] border-r  mt-[64px]'>
              <Card className='p-2 mt-2 border-none shadow-none'>
                <AccordionLeftbar/>
              </Card>
            </section>
            {/* md:ml-[15%] */}
            <section className='w-full  mt-[64px]'>


              <Card className="border-none h-[calc(100vh-64px)] shadow-none p-1">
                  
                {children}
              </Card>

            </section>
      

    </div>

          
        </ThemeProvider>
        
        </body>
    </html>
  )
}


